name: Discord Bot 24/7

on:
  schedule:
    - cron: '* * * * *'  # Run every minute
  workflow_dispatch:

concurrency:
  group: discord-bot
  cancel-in-progress: true

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    timeout-minutes: 0.75  # 45 seconds timeout

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        TARGET_USER_ID: ${{ secrets.TARGET_USER_ID }}
        GH_PAT_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
      run: |
        timeout 45s python main.py  # Force stop after 45 seconds

    - name: Cleanup
      if: always()
      run: |
        echo "Cleaning up resources..."