name: snarky-discord-bot 24/7

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

concurrency:
  group: discord-bot
  cancel-in-progress: true

jobs:
  keep_alive:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        TARGET_USER_ID: ${{ secrets.TARGET_USER_ID }}
        GH_PAT_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
      run: |
        nohup python main.py &
        
    - name: Cleanup
      if: always()
      run: |
        echo "Cleaning up and preparing for next run..."