name: Discord Bot 24/7

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run Bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        TARGET_USER_ID: ${{ secrets.TARGET_USER_ID }}
        GITHUB_PAT_TOKEN: ${{ secrets.GITHUB_PAT_TOKEN }}
      run: python main.py