name: Discord Bot 24/7

on:
  schedule:
    - cron: '0/6 * * * *'  # Run every 6 minutes (5 min run + 1 min break)
  workflow_dispatch:

concurrency:
  group: discord-bot
  cancel-in-progress: true

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Force stop after 5 minutes

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        TARGET_USER_ID: ${{ secrets.TARGET_USER_ID }}
        GH_PAT_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
      run: |
        python main.py
        
    - name: Cleanup
      if: always()
      run: |
        echo "Cleaning up and preparing for next run..."